dbt_pipeline_3:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' 
      host: 'airflow-sqlserver-1'
      port: 1433
      database: projectBI_DW
      schema: dbo
      user: sa
      password: password123
      trust_cert: True

  target: dev