dbt_pipeline_2:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      trust_cert: true
      host: 'airflow-sqlserver-1'
      port: 1433
      database: projectBI_NDS
      schema: dbo
      user: sa
      password: password123
      encrypt: False

  target: dev