version: 2

models:
  - name: customer
    columns:
      - name: CustomerID
        tests:
          - unique
          - not_null
          
      - name: TerritoryID
        tests:
          - relationships:
              to: ref('territory')
              field: TerritoryID

  - name: employee
    columns:
      - name: EmployeeID
        tests:
          - unique
          - not_null

  - name: product
    columns:
      - name: ProductID
        tests:
          - unique
          - not_null

  - name: store
    columns:
      - name: StoreID
        tests:
          - unique
          - not_null

      - name: SalesPersonID
        tests:
          - relationships:
              to: ref('employee')
              field: EmployeeID

  - name: territory
    columns:
      - name: TerritoryID
        tests:
          - unique
          - not_null

  - name: sale_order
    columns:
      - name: SalesOrderID
        tests:
          - unique
          - not_null

      - name: CustomerID
        tests:
          - relationships:
              to: ref('customer')
              field: CustomerID

      - name: SalesPersonID
        tests:
          - relationships:
              to: ref('employee')
              field: EmployeeID

      - name: TerritoryID
        tests:
          - relationships:
              to: ref('territory')
              field: TerritoryID

      - name: Currency
        tests:
          - relationships:
              to: ref('currency_rate')
              field: ToCurrencyCode

  - name: sale_order_detail
    columns:
      - name: SalesOrderDetailID
        tests:
          - unique
          - not_null

      - name: ProductID
        tests:
          - relationships:
              to: ref('product')
              field: ProductID