DW:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: MSI
      port: 1433
      database: project_BI_DW
      schema: dbo
      user: sa
      password: "123456"
      trust_cert: True

  target: dev